# Generated by Django 4.2.11 on 2024-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
